version: '3.8'

services:
  api:
    build: ./api/
    env_file: ./api/.envrc
    volumes:
      - ./api/:/usr/src/app:rw
    ports:
      - "3001:3001"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    env_file: ./api/.envrc
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  ui:
    build: ./ui/
    env_file: ./ui/.envrc
    volumes:
      - ./ui:/app:rw
    ports:
      - "3000:3000"
    depends_on:
      - api
